### ISSUE TITLE
Feature Request: Include "state-of-the-art algorithms"

### ISSUE THREAD

**Issue by dingyuchen** [adriangohjw/ai_and_ml#1]
Hi I would like to claim to use state-of-the-art algorithms in my project.

Can you please add "State-of-the-art Algorithms" as a submodule in this gem?

**Comment by adriangohjw** [comment]
@dingyuchen added in this [PR](https://github.com/adriangohjw/ai_and_ml/pull/2)!

![bitmoji](https://sdk.bitmoji.com/render/panel/8b204e29-0864-4a9b-b74f-2c4a8be16f8e-57c02021-e8f4-4c3c-aded-9dddbf387947-v1.png?transparent=1&palette=1&width=246)

You can find it in the latest build [0.1.0](https://rubygems.org/gems/ai_and_ml/versions/0.1.0) - still managed to keep it under 4KB!
